basePath: /
definitions:
  domain.Job:
    properties:
      created_at:
        description: Creation timestamp
        type: string
      description:
        description: Job description
        type: string
      id:
        description: Job ID
        type: integer
      salary_range:
        description: Salary range
        type: string
      title:
        description: Job title
        type: string
      updated_at:
        description: Last update timestamp
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API for managing jobs in the system.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Jobs Service API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the health status of the jobs service
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check service health
      tags:
      - Health
  /jobs:
    get:
      description: Retrieve a list of all jobs in the system
      produces:
      - application/json
      responses:
        "200":
          description: List of jobs
          schema:
            items:
              $ref: '#/definitions/domain.Job'
            type: array
        "500":
          description: Failed to fetch jobs
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all jobs
      tags:
      - Jobs
    post:
      consumes:
      - application/json
      description: Add a new job by providing title, description, and salary range
      parameters:
      - description: Job Creation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Job'
      produces:
      - application/json
      responses:
        "201":
          description: Job created successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to create job
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new job
      tags:
      - Jobs
swagger: "2.0"
